# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M_dbSLvctO-IXexsYQG-45Gl6b36O1zk
"""

import os
import random
import smtplib

# Generate OTP
digits = "0123456789"
OTP = ''.join(random.choices(digits, k=6))
otp_message = f"{OTP} is your OTP"

# Email details
sender_email = "Your Gmail Account"
receiver_email = input("Enter your email: ")
password = "Your App Password"

# Sending email
try:
    with smtplib.SMTP('smtp.gmail.com', 587) as s:
        s.starttls()
        s.login(sender_email, password)
        s.sendmail(sender_email, receiver_email, otp_message)
        print("OTP sent successfully!")
except Exception as e:
    print(f"Failed to send email: {e}")

# OTP verification
user_otp = input("Enter Your OTP >>: ")
if user_otp == OTP:
    print("Verified")
else:
    print("Please check your OTP again")